Description of guiRunner
guiRunner
PURPOSE
GUIRUNNER Summary of this function goes here
SYNOPSIS
function [ detrended, R_loc, validLocs ] = guiRunner(sigNum)
DESCRIPTION
GUIRUNNER Summary of this function goes here
   Detailed explanation goes here
CROSS-REFERENCE INFORMATION
This function calls:
loadSig loadSig Loads a signal from our limited dataset
preprocessingNew preprocessingNew Pre-processing of ECG signal
kota kota QRS detection using Hilbert Transform
ensembleMethods GETENSEMBLEAVERAGE Gets the average of all QRS peaks
plotResult PLOTRESULT Summary of this function goes here
This function is called by:
main MAIN MATLAB code for main.fig
SOURCE CODE
function [ detrended, R_loc, validLocs ] = guiRunner(sigNum)
%GUIRUNNER Summary of this function goes here
%   Detailed explanation goes here
[ sig, fs ] = loadSig(sigNum);
% Pre-processing
[ sig, detrended ] = preprocessingNew(sig, fs);
% Kota
[ R_loc ] = kota(sig, detrended);
validLocs = ones(1,length(R_loc));
windowSize = 100;
[ validLocs ] = ensembleMethods(detrended, R_loc, validLocs, windowSize);
plotResult(detrended, R_loc, validLocs, fs);
end