clear all;
close all;

numSamples = 500000;
record = 'infant1_ecg';
plot = 1;

result = hrvDetect(record, 'n_sample_start', 1 , ...
    'n_sample_end', numSamples, ...
    'ensemble_filter_threshold', 0.1, ...
    'mad_filter_threshold', 20, ...
    'missed_beats_tolerance_percent', 20, ...
    'median_filter_window', 1, ...
    'interpolation_method','linear', ...
    'smoothing_spline_coef', 0.9);

[ precision, recall, f_score, jitter ] = compareWithPhysio( record, result, numSamples, 15, plot );